name: CI
on:
  push:
    branches:
      - main
      - r[1-9]
  pull_request:
    branches:
      - main
      - r[1-9]
jobs:
  build-and-push-monitoring-data-persistor:
    name: Build and push monitoring-data-persistor
    uses: eu-nebulous/github-actions/.github/workflows/build-and-push-container-image.yml@main
    with:
      context: monitoring-data-persistor
      image-name: monitoring-data-persistor 
    secrets: inherit
